version: '3'
services:

  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      # to sync the files from the host to the container
      - .:/app
      # protects the files from being overwritten
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - config/dev.env
    command: npm run dev

    
  mongoDB:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root