version: '3'
services:
  nginx:
    ports:
      - 80:80
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    # ports:
    #   - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
    # env_file:
    #   - config/prod.env
    command: node src/index.js
  mongoDB:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}