version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
    # - binding nginx-config-volume to :/etc/nginx/conf.d
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: johnmerga/node-app
    depends_on:
    # - start mongo before app
      - mongoDB
  mongoDB:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
    # - giving a name to mongo data volume
      - mongo-db:/data/db
  redis:
    image: redis
    # ports:
    # - 6379:6379
    # - giving a name to redis data volume
    # volumes:
    #   - redis-data:/data  


# - declaring the mongo data volume      
volumes:
  mongo-db:
  # redis-data:
  