version: '3'
services:
  node-app:
    build: .
    depends_on:
    # - start mongo before app
      - mongoDB
  mongoDB:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
    # - giving a name to mongo data volume
      - mongo-db:/data/db

# - declaring the mongo data volume      
volumes:
  mongo-db: