version: '3'
services:
  nginx:
    ports:
      - 80:80
  node-app:
    deploy: # configuring docker-compose to use docker swarm
      replicas: 8 # how many instances of specific service you want to run
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s

    build: 
      context: .
      args:
        NODE_ENV: production
    # ports:
    #   - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
    # env_file:
    #   - config/prod.env
    command: node src/index.js
  mongoDB:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}