version: '3'
services:
  nginx:
    ports:
      - 80:80
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    # ports:
    #   - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - config/prod.env
    command: node src/index.js